# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wheather Forecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wheather Forecast
  pod 'Alamofire'
  pod 'TinyConstraints'
  pod 'SDWebImage', '~> 5.18'
  pod 'IQKeyboardManager', '~> 6.5'

  target 'Wheather ForecastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Wheather ForecastUITests' do
    # Pods for testing
  end

end
